platform: linux/${arch}

clone:
  git:
    image: syncloud/drone-git-${arch}
    depth: 50

pipeline:

  bootstrap:
    image: syncloud/build-deps-${arch}
    secrets: [ARTIFACT_SSH_KEY, DOCKER_USERNAME, DOCKER_PASSWORD]
    commands:
      - ./bootstrap/bootstrap.sh ${arch}
      - ./upload-artifact.sh bootstrap-${arch}.tar.gz
      - ./docker/build-bootstrap.sh ${arch}
    privileged: true
    volumes:
      - /usr/bin/docker:/usr/bin/docker
      - /var/run/docker.sock:/var/run/docker.sock

  rootfs:
    image: syncloud/build-deps-${arch}
    commands:
      - ./rootfs.sh rc stable ${arch}
    privileged: true
    network_mode: host
    volumes:
      - /usr/bin/docker:/usr/bin/docker
      - /var/run/docker.sock:/var/run/docker.sock

  test-syncloud:
    image: syncloud/build-deps-${arch}
    commands:
      - ./integration/test-docker.sh teamcity@syncloud.it password teamcity master syncloud root syncloud
    privileged: true
      
  test-stretch:
    image: syncloud/build-deps-${arch}
    commands:
      - ./integration/test-docker.sh teamcity@syncloud.it password teamcity master stretch debian debian
    privileged: true
    when:
      platform: linux/amd64

  upload-artifact:
    image: syncloud/build-deps-${arch}
    secrets: [ARTIFACT_SSH_KEY]
    commands:
      - ./upload-artifact.sh rootfs-${arch}.tar.gz
    privileged: true

  upload-docker:
    image: syncloud/build-deps-${arch}
    secrets: [DOCKER_USERNAME, DOCKER_PASSWORD]
    commands:
      - ./docker/build-rootfs.sh ${arch}
      - ./docker/build-systemd.sh ${arch}
    privileged: true
    network_mode: host
    volumes:
      - /usr/bin/docker:/usr/bin/docker
      - /var/run/docker.sock:/var/run/docker.sock

#  ci-artifact:
#    image: syncloud/build-deps-${arch}
#    secrets: [ARTIFACT_SSH_KEY]
#    commands:
#      - ./upload-artifact.sh integration/log ci/$DRONE_BUILD_NUMBER-$(dpkg --print-architecture)
#    when:
#      status: [ failure, success ] 
      
services:
  syncloud:
    image: syncloud/systemd-${arch}
    privileged: true
    volumes:
      - /var/run/dbus:/var/run/dbus
      
  stretch:
    image: minimum2scp/systemd-stretch
    privileged: true
    volumes:
      - /var/run/dbus:/var/run/dbus
    when:
      platform: linux/amd64
     
matrix:
  arch:
    - amd64
    - arm