platform: linux/${arch}

clone:
  git:
    image: syncloud/drone-git-${arch}
    depth: 50

pipeline:
  rootfs:
    image: syncloud/rootfs-deps-${arch}
    secrets: [ARTIFACT_SSH_KEY]
    commands:
      - ./bootstrap/bootstrap.sh
      - ./upload-artifact.sh rootfs-$(dpkg --print-architecture).tar.gz
    privileged: true
 
  syncloud-rootfs:
    image: syncloud/rootfs-deps-${arch}
    secrets: [ARTIFACT_SSH_KEY]
    commands:
      - ./rootfs.sh rc stable
      - ./upload-artifact.sh syncloud-rootfs-$(dpkg --print-architecture).tar.gz
    privileged: true
 
#  test:
#    image: syncloud/rootfs-deps-${arch}
#    commands:
#      - ./integration/test-docker.sh teamcity@syncloud.it password teamcity master device ${installer}
#    privileged: true
     
#  ci-artifact:
#    image: syncloud/rootfs-deps-${arch}
#    secrets: [ARTIFACT_SSH_KEY]
#    commands:
#      - ./upload-artifact.sh integration/log ci/$DRONE_BUILD_NUMBER-$(dpkg --print-architecture)
#    when:
#      status: [ failure, success ] 
      
services:
  device:
    image: syncloud/systemd-${arch}
    privileged: true
    volumes:
      - /var/run/dbus:/var/run/dbus
     
matrix:
  arch:
    - arm
    - amd64
  installer:
    - sam
    #- snapd
