platform: linux/${arch}

clone:
  git:
    image: syncloud/drone-git-${arch}
    depth: 50

pipeline:

  rootfs:
    image: syncloud/build-deps-${arch}
    secrets: [ARTIFACT_SSH_KEY]
    commands:
      - ./bootstrap/bootstrap.sh ${arch}
      - ./upload-artifact.sh rootfs-${arch}.tar.gz
    privileged: true
    
  syncloud-rootfs:
    image: syncloud/build-deps-${arch}
    secrets: [ARTIFACT_SSH_KEY]
    commands:
      - ./rootfs.sh rc stable ${installer} ${arch}
      - ./upload-artifact.sh syncloud-rootfs-${arch}-${installer}.tar.gz
    privileged: true
    network_mode: host
    volumes:
      - /usr/bin/docker:/usr/bin/docker
      - /var/run/docker.sock:/var/run/docker.sock
      
#  test:
#    image: syncloud/build-deps-${arch}
#    commands:
#      - ./integration/test-docker.sh teamcity@syncloud.it password teamcity master device ${installer}
#    privileged: true
     
#  ci-artifact:
#    image: syncloud/build-deps-${arch}
#    secrets: [ARTIFACT_SSH_KEY]
#    commands:
#      - ./upload-artifact.sh integration/log ci/$DRONE_BUILD_NUMBER-$(dpkg --print-architecture)
#    when:
#      status: [ failure, success ] 
      
#services:
#  device:
#    image: syncloud/systemd-${arch}
#    privileged: true
#    volumes:
#      - /var/run/dbus:/var/run/dbus
     
matrix:
  arch:
    - amd64
    - arm
  installer:
    - snapd
    - sam
