---
kind: pipeline
name: arm

platform:
  os: linux
  arch: arm

steps:
- name: bootstrap
  image: syncloud/build-deps-arm
  commands:
  - ./bootstrap/bootstrap.sh arm
  - ./upload-artifact.sh bootstrap-arm.tar.gz
  - ./docker/build-bootstrap.sh arm
  environment:
    ARTIFACT_SSH_KEY:
      from_secret: ARTIFACT_SSH_KEY
    DOCKER_PASSWORD:
      from_secret: DOCKER_PASSWORD
    DOCKER_USERNAME:
      from_secret: DOCKER_USERNAME
  privileged: true
  volumes:
  - name: docker
    path: /usr/bin/docker
  - name: docker.sock
    path: /var/run/docker.sock

- name: rootfs
  image: syncloud/build-deps-arm
  commands:
  - ./rootfs.sh stable stable arm
  privileged: true
  volumes:
  - name: docker
    path: /usr/bin/docker
  - name: docker.sock
    path: /var/run/docker.sock

- name: rootfs-ci-artifact
  image: syncloud/build-deps-arm
  commands:
  - ./upload-artifact.sh integration/log ci/$DRONE_BUILD_NUMBER-syncloud-$(dpkg --print-architecture)
  environment:
    ARTIFACT_SSH_KEY:
      from_secret: ARTIFACT_SSH_KEY
  when:
    status:
    - failure
    - success

- name: upload-artifact
  image: syncloud/build-deps-arm
  commands:
  - ./upload-artifact.sh rootfs-arm.tar.gz
  environment:
    ARTIFACT_SSH_KEY:
      from_secret: ARTIFACT_SSH_KEY
  privileged: true

- name: upload-docker
  image: syncloud/build-deps-arm
  commands:
  - ./docker/build-rootfs.sh arm
  - ./docker/build-systemd.sh arm
  environment:
    DOCKER_PASSWORD:
      from_secret: DOCKER_PASSWORD
    DOCKER_USERNAME:
      from_secret: DOCKER_USERNAME
  privileged: true
  volumes:
  - name: docker
    path: /usr/bin/docker
  - name: docker.sock
    path: /var/run/docker.sock

services:
- name: syncloud
  image: syncloud/systemd-arm
  privileged: true
  volumes:
  - name: dbus
    path: /var/run/dbus

volumes:
- name: dbus
  host:
    path: /var/run/dbus
- name: docker
  host:
    path: /usr/bin/docker
- name: docker.sock
  host:
    path: /var/run/docker.sock

---
kind: pipeline
name: amd64

platform:
  os: linux
  arch: amd64

steps:
- name: bootstrap
  image: syncloud/build-deps-amd64
  commands:
  - ./bootstrap/bootstrap.sh amd64
  - ./upload-artifact.sh bootstrap-amd64.tar.gz
  - ./docker/build-bootstrap.sh amd64
  environment:
    ARTIFACT_SSH_KEY:
      from_secret: ARTIFACT_SSH_KEY
    DOCKER_PASSWORD:
      from_secret: DOCKER_PASSWORD
    DOCKER_USERNAME:
      from_secret: DOCKER_USERNAME
  privileged: true
  volumes:
  - name: docker
    path: /usr/bin/docker
  - name: docker.sock
    path: /var/run/docker.sock

- name: rootfs
  image: syncloud/build-deps-amd64
  commands:
  - ./rootfs.sh stable stable amd64
  privileged: true
  volumes:
  - name: docker
    path: /usr/bin/docker
  - name: docker.sock
    path: /var/run/docker.sock

- name: rootfs-ci-artifact
  image: syncloud/build-deps-amd64
  commands:
  - ./upload-artifact.sh integration/log ci/$DRONE_BUILD_NUMBER-syncloud-$(dpkg --print-architecture)
  environment:
    ARTIFACT_SSH_KEY:
      from_secret: ARTIFACT_SSH_KEY
  when:
    status:
    - failure
    - success

- name: upload-artifact
  image: syncloud/build-deps-amd64
  commands:
  - ./upload-artifact.sh rootfs-amd64.tar.gz
  environment:
    ARTIFACT_SSH_KEY:
      from_secret: ARTIFACT_SSH_KEY
  privileged: true

- name: upload-docker
  image: syncloud/build-deps-amd64
  commands:
  - ./docker/build-rootfs.sh amd64
  - ./docker/build-systemd.sh amd64
  environment:
    DOCKER_PASSWORD:
      from_secret: DOCKER_PASSWORD
    DOCKER_USERNAME:
      from_secret: DOCKER_USERNAME
  privileged: true
  volumes:
  - name: docker
    path: /usr/bin/docker
  - name: docker.sock
    path: /var/run/docker.sock

services:
- name: syncloud
  image: syncloud/systemd-amd64
  privileged: true
  volumes:
  - name: dbus
    path: /var/run/dbus

volumes:
- name: dbus
  host:
    path: /var/run/dbus
- name: docker
  host:
    path: /usr/bin/docker
- name: docker.sock
  host:
    path: /var/run/docker.sock

...
