---
kind: pipeline
name: arm

platform:
  os: linux
  arch: arm

steps:
- name: bootstrap
  image: syncloud/build-deps-arm
  commands:
  - ./bootstrap/bootstrap.sh
  privileged: true

- name: rootfs
  image: syncloud/build-deps-arm
  commands:
  - ./rootfs.sh arm
  network_mode: host
  privileged: true
  volumes:
  - name: docker
    path: /usr/bin/docker
  - name: docker.sock
    path: /var/run/docker.sock

- name: upload-docker
  image: syncloud/build-deps-arm
  commands:
  - ./docker/build-rootfs.sh arm
  network_mode: host
  environment:
    DOCKER_PASSWORD:
      from_secret: DOCKER_PASSWORD
    DOCKER_USERNAME:
      from_secret: DOCKER_USERNAME
  privileged: true
  volumes:
  - name: docker
    path: /usr/bin/docker
  - name: docker.sock
    path: /var/run/docker.sock

- name: artifact
  image: appleboy/drone-scp
  settings:
    command_timeout: 2m
    host:
      from_secret: artifact_host
    key:
      from_secret: artifact_key
    source:
    - integration/log/*
    - rootfs-arm.tar.gz
    target: /home/artifact/repo/rootfs/${DRONE_BUILD_NUMBER}-arm
    timeout: 2m
    username: artifact
  when:
    status:
    - failure
    - success

volumes:
- name: dbus
  host:
    path: /var/run/dbus
- name: docker
  host:
    path: /usr/bin/docker
- name: docker.sock
  host:
    path: /var/run/docker.sock

---
kind: pipeline
name: amd64

platform:
  os: linux
  arch: amd64

steps:
- name: bootstrap
  image: syncloud/build-deps-amd64
  commands:
  - ./bootstrap/bootstrap.sh
  privileged: true

- name: rootfs
  image: syncloud/build-deps-amd64
  commands:
  - ./rootfs.sh amd64
  network_mode: host
  privileged: true
  volumes:
  - name: docker
    path: /usr/bin/docker
  - name: docker.sock
    path: /var/run/docker.sock

- name: upload-docker
  image: syncloud/build-deps-amd64
  commands:
  - ./docker/build-rootfs.sh amd64
  network_mode: host
  environment:
    DOCKER_PASSWORD:
      from_secret: DOCKER_PASSWORD
    DOCKER_USERNAME:
      from_secret: DOCKER_USERNAME
  privileged: true
  volumes:
  - name: docker
    path: /usr/bin/docker
  - name: docker.sock
    path: /var/run/docker.sock

- name: artifact
  image: appleboy/drone-scp
  settings:
    command_timeout: 2m
    host:
      from_secret: artifact_host
    key:
      from_secret: artifact_key
    source:
    - integration/log/*
    - rootfs-amd64.tar.gz
    target: /home/artifact/repo/rootfs/${DRONE_BUILD_NUMBER}-amd64
    timeout: 2m
    username: artifact
  when:
    status:
    - failure
    - success

volumes:
- name: dbus
  host:
    path: /var/run/dbus
- name: docker
  host:
    path: /usr/bin/docker
- name: docker.sock
  host:
    path: /var/run/docker.sock

...
