---
kind: pipeline
name: buster-arm

platform:
  os: linux
  arch: arm

steps:
- name: bootstrap
  image: syncloud/build-deps-arm
  commands:
  - ./bootstrap/bootstrap-buster.sh
  privileged: true

- name: build
  image: syncloud/build-deps-arm
  commands:
  - ./build.sh buster arm
  network_mode: host
  privileged: true
  volumes:
  - name: docker
    path: /usr/bin/docker
  - name: docker.sock
    path: /var/run/docker.sock

- name: test
  image: syncloud/build-deps-arm
  commands:
  - ./test.sh buster arm
  network_mode: host
  privileged: true
  volumes:
  - name: docker
    path: /usr/bin/docker
  - name: docker.sock
    path: /var/run/docker.sock

- name: cleanup
  image: syncloud/build-deps-arm
  commands:
  - ./cleanup.sh
  network_mode: host
  privileged: true
  volumes:
  - name: docker
    path: /usr/bin/docker
  - name: docker.sock
    path: /var/run/docker.sock
  when:
    status:
    - failure
    - success

- name: docker
  image: syncloud/build-deps-arm
  commands:
  - ./docker/push-platform.sh buster arm
  network_mode: host
  environment:
    DOCKER_PASSWORD:
      from_secret: DOCKER_PASSWORD
    DOCKER_USERNAME:
      from_secret: DOCKER_USERNAME
  privileged: true
  volumes:
  - name: docker
    path: /usr/bin/docker
  - name: docker.sock
    path: /var/run/docker.sock

- name: artifact
  image: appleboy/drone-scp
  settings:
    command_timeout: 2m
    host:
      from_secret: artifact_host
    key:
      from_secret: artifact_key
    source:
    - integration/log/*
    - log/*
    - rootfs-buster-arm.tar.gz
    target: /home/artifact/repo/rootfs/${DRONE_BUILD_NUMBER}-buster-arm
    timeout: 2m
    username: artifact
  when:
    status:
    - failure
    - success

volumes:
- name: dbus
  host:
    path: /var/run/dbus
- name: docker
  host:
    path: /usr/bin/docker
- name: docker.sock
  host:
    path: /var/run/docker.sock

...
